eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://192.168.0.109:3306/springcloud_sell?characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    database: MYSQL
    show-sql: true
server:
  port: 8083

env:
  dev1237777
